version: 0.2

phases:
  pre_build:
    commands:
      - echo "Cleaning and building the JAR file..."
      - mvn clean package -DskipTests
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:latest .
      - docker tag 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:latest 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:latest
      - docker push 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"course-service","imageUri":"%s"}]' 920373016288.dkr.ecr.us-east-1.amazonaws.com/chandu22-registry:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/springboot-docker-aws-ecs-codebuild.jar
